# Generated by Django 5.2.5 on 2025-08-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='uploads/cv/')),
                ('jd_file', models.FileField(upload_to='uploads/jd/')),
                ('cv_text', models.TextField()),
                ('jd_text', models.TextField()),
                ('match_percent', models.FloatField(blank=True, null=True)),
                ('cv_keywords', models.JSONField(blank=True, null=True)),
                ('jd_keywords', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
