# Generated by Django 5.2.5 on 2025-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cv/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/jd/'),
        ),
    ]
