# Generated by Django 5.2.5 on 2025-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analysis_cv_file_alter_analysis_jd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
